# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-HideCursor
version:      0.02
version_from: lib/Tk/HideCursor.pm
installdirs:  site
requires:
    Tk:                            800.022

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
